### ISSUE TITLE
Issue with LCO facilities coordinates

### ISSUE THREAD

**Issue by moira-andrews** [TOMToolkit/tom_base#1017]
There is a discrepancy between LCO facilities coordinates in TOMToolkit and snex that is causing errors. Here is an example error that occurred when triggering an observation, even though our airmass plots show that the target should be visible longer than the observation request.
![image](https://github.com/user-attachments/assets/ae76b742-1781-46a0-b215-30b0355c772e)

Checking tom_observations/facilities/lco.py and comparing to the [LCO website](https://lco.global/observatory/sites/), which matches snex, some of the sites' coordinates are off. The error described above is likely due to TOMToolkit calculating the visibility from faulty coordinates. 

Here are the proposed changes in the coordinates of tom_observations/facilities/lco.py: 

`'Siding Spring': {
                'sitecode': 'coj',
                'latitude': -31.272 —> -31.2733
                'longitude': 149.07 —> 149.438
                'elevation': 1116
            },
'Sutherland': {
                'sitecode': 'cpt',
                'latitude': -32.38 —> -32.3826
                'longitude': 20.81 —> 20.8124
                'elevation': 1804
            },
'Teide': {
                'sitecode': 'tfn',
                'latitude': 20.3 —> 28.3
                'longitude': -16.511 —> -16.50972
                'elevation': 2390
            },
'Cerro Tololo': {
                'sitecode': 'lsc',
                'latitude': -30.167 —> -30.167367
                'longitude': -70.804 —> -70.8049
                'elevation': 2198
            },
'McDonald': {
                'sitecode': 'elp',
                'latitude': 30.679 —> 30.679833
                'longitude': -104.015 —> -104.015173
                'elevation': 2027
            },
'Haleakala': {
                'sitecode': 'ogg',
                'latitude': 20.706 —> 20.706900
                'longitude': -156.258 —> -156.25800
                'elevation': 3065
            }`

**Comment by jchate6** [comment]
@moira-andrews Thanks for bringing this to our attention!
Most of these changes are too small to actually affect observations. (Teide is definitely a typo and needs to be fixed.)
This is most likely being caused by moon and HA constraints that are not taken into account here.

See https://github.com/TOMToolkit/tom_base/issues/752

**Comment by jchate6** [comment]
@moira-andrews 
SNex2 is using its own airmass plot (also an entirely different target detail page), so updates to the TOM Base plots wouldn't help you directly.

If you wish to add hour angles or more complexity to your plot, you can do so [here](https://github.com/LCOGT/snex2/blob/946a6a52ae3f1be70771564c5acb39ae15acc55f/custom_code/templatetags/custom_code_tags.py#L74)

**Comment by crpellegrino** [comment]
The SNEx2 airmass issues are partially fixed in SNEx2 [PR 28](https://github.com/LCOGT/snex2/pull/28)

**Comment by jchate6** [comment]
> The SNEx2 airmass issues are partially fixed in SNEx2 [PR 28](https://github.com/LCOGT/snex2/pull/28)

Nice!
