### ISSUE TITLE
Lasair settings dictionary has wrong case key + multiple API keys needed in future

### ISSUE THREAD

**Issue by talister** [TOMToolkit/tom_base#1062]
**Describe the bug**
This bug report is in two parts, the second part may be better spun-off into a separate feature request.

1. The dictionary key for holding the Lasair API key in the `BROKERS` section of the [tom_setup/templates/tom_setup/settings.tmpl](https://github.com/TOMToolkit/tom_base/blob/ae1c514e9d6a23ebc1b30a0b072f0ee3a60f61f3/tom_setup/templates/tom_setup/settings.tmpl#L276) has the incorrect case (`Lasair` vs `LASAIR`) causing attempts to use the Lasair broker within TOM Toolkit to break (specifically attempts to use `tom_alerts/brokers/lasair.LasairBroker.fetch_alerts()`) 
2. Lasair-ZTF and Lasair-LSST (currently?) require separate accounts which have separate API keys; support for handling both flavors of broker and their separate API keys should be added, particularly as ZTF is funded to continue for the next 2 years.

**To Reproduce**
1. Start with a new version of `tomtoolkit` and run `python ./manage.py tom_setup` (or use `make-tom/make-tom.sh`)
2. Add Lasair API key to the `api_key` section of `['BROKERS']['Lasair']` in the `settings.py` and attempt to use the Lasair Query form
3. Fails with `Requires a 'api_key' in settings.BROKERS['LASAIR']. Log in or create an account at https://lasair-ztf.lsst.ac.uk/ to acquire an API token.`

**Expected behavior**
Queries should work. Support for querying both ZTF and LSST through Lasair is desirable.

**Desktop (please complete the following information):**
- OS: Windows 11
- Browser: Firefox
- Version 130.0.1
- Python Version: 3.10.11
- TOM Toolkit Version: 2.19.6

**Additional context**

**Comment by jchate6** [comment]
#1061 would help catch these in the future.

**Comment by jchate6** [comment]
This is correct in the [docs](https://tom-toolkit.readthedocs.io/en/latest/api/tom_alerts/brokers.html) but not in the template.

**Comment by jchate6** [comment]
I spun off the 2nd part of this into issue #1066
