### ISSUE TITLE
Paging observation data

### ISSUE THREAD

**Issue by zemogle** [TOMToolkit/tom_base#123]
If an observation has more than 50 data files, the rest aren't shown and there is no way to get to them. It would be useful either show a complete list or have a way to navigate to the additional data.

**Comment by Ara-yjx** [comment]
> If an observation has more than 50 data files, the rest aren't shown and there is no way to get to them. It would be useful either show a complete list or have a way to navigate to the additional data.

@zemogle Hello! Could you please provide us more information regarding this issue? Which page are the files not shown on? We have checked the observation detail page and the data tab of the target detail page, and both pages can display more than 50 files. Thanks!

**Comment by zemogle** [comment]
Its the observation record (i.e. the only place you can save data from). I'm not sure how to demonstrate this to you (because it requires a request which has more than 50 image files) but I've checked again today and it is definitely a problem. You can emulate this by finding a request in the Observing Portal which has an exposure count > 50.

**Comment by zemogle** [comment]
Some more digging on this. The issue happens because `archive-api.lco.global` returns a max 100 results by default (half of which are raw, half reduced - hence the 50). This is probably the default in `django-rest-framework`.

I suggest that if the `archive-api` payload returns a non-null `next` parameter that it should be called, recursively until all the data for a request is found.

**Comment by Ara-yjx** [comment]
@zemogle This information is very helpful. Thanks! We're working on it.

**Comment by zemogle** [comment]
Thanks!
