### ISSUE TITLE
Workshop Material

### ISSUE THREAD

**Issue by Fingel** [TOMToolkit/tom_base#131]
- [ ] Research existing introduction to Django workshop material (DjangoCon?)
- [ ] Presentation on the motivation for the use of Django
- [ ] Write Django for astronomers tutorial
- [ ] Live coding demo of writing an alert broker
- [ ] Short customization tutorials for various aspects of the the toolkit

**Comment by dmcollom** [comment]
Given that the workshop is complete, I think this can be closed.
