### ISSUE TITLE
Missing parameters submitting a SOAR observation request from a TOM

### ISSUE THREAD

**Issue by rachel3834** [TOMToolkit/tom_base#135]
I attempted to submit a request for a SOAR/Goodman imaging observation using the UI provided by default in the TOM.  I was able to configure the request OK, but got the following errors when I hit submit:
telescope_class: "soa" is not a valid choice.
non_field_errors: Rotator Mode SKY requires [rotator_angle] set in extra params

**Comment by dmcollom** [comment]
This is addressed by PR #147 and will be fixed in the next release.

**Comment by dmcollom** [comment]
With the release of 0.7.0, this can be closed.
