### ISSUE TITLE
Default form for imaging versus spectroscopic observations

### ISSUE THREAD

**Issue by rachel3834** [TOMToolkit/tom_base#136]
By default, the Toolkit provides a simple form for requesting imaging observations.  Of course this can be user customized, but it is very much a form for requesting imaging observations, and its rather confusing to have some - but not all - of the options necessary for a spectroscopic request appearing in the menu.  

Users might find this less confusing if we provided two default observation request forms: one for spectra and one for imaging requests.

**Comment by dmcollom** [comment]
This has been addressed in #150 and will be in the next release.

**Comment by dmcollom** [comment]
With the release of 0.7.0, this can be closed.
