### ISSUE TITLE
Deleting comments on target pages redirects to example.com

### ISSUE THREAD

**Issue by jfrostburke** [TOMToolkit/tom_base#152]
For example, when the user SNEx Secure tries to delete a comment that says "test" on snex2 it first correctly redirects me to a confirmation page (e.g. https://test.supernova.exchange/comment/12/delete) that asks me "Are you sure you want to delete "SNEx Secure: test..."?" But once I press the "Confirm" button, it redirects me to http://example.com/targets/4575/#c12. Part of this URL is correct (/targets/4575), but the example.com is clearly wrong.

This happens both on snex2 (which is dockerized) and on David's local `manage.py runserver` TOM.

**Comment by Fingel** [comment]
Hm, this probably has to do with the sites framework, in your admin page (/admin/) go to sites and edit the site there, change example.com to something else.
Still, this is a bug, it shouldn't use the sites framework and should just redirect to the current page.

**Comment by jfrostburke** [comment]
I saw that you added a [General Deployment Tips](https://tomtoolkit.github.io/docs/deployment_tips) page to the documentation, which has some of what you said here about the /admin/ page. I don't see `/admin/` or `example.com` anywhere in my project, but I do see `/admin/`s listed when I do `./manage.py show_urls`.

Is it correct to add `path('admin/', 'test.supernova.exchange')` to my `urls.py` like [here](https://docs.djangoproject.com/en/2.2/ref/contrib/admin/#hooking-adminsite-to-urlconf), or should I follow more of that guide and create my own admin site and add it to `settings.py`?

**Comment by jfrostburke** [comment]
Okay so to fix this I had to do two things:

1. As suggested, I went to https://test.supernova.exchange/admin/ and edited Sites, adding the URL (test.supernova.exchange).
2. This broke everything until I edited my `settings.py` and changed `SITE_ID` to 2.

**Comment by Fingel** [comment]
That'll do it. Probably best to change the site object with id of 1 to the correct url. I'm guessing you deleting the existing one and added another.
Ideally the comments package would not depend on the sites framework. It's 3rd party though so that might be difficult to work with. We'll take a look though.

**Comment by dmcollom** [comment]
Given that this has been addressed in the docs, I'm going to close this unless someone else runs into it.
