### ISSUE TITLE
Read spectrum observation date/time from FITS headers when available

### ISSUE THREAD

**Issue by griffin-h** [TOMToolkit/tom_base#156]
When uploading a spectroscopy observation, the user is required to input an observation date and time. If the upload is a FITS file, this information is very likely to be in the header under a small number of different header keywords: DATE, DATE-OBS, TIME, TIME-OBS, MJD, MJD-OBS. It would be helpful to automatically populate this when possible, at least for LCO/FLOYDS, SOAR/Goodman, and Gemini/GMOS spectra.

**Comment by dmcollom** [comment]
This has been addressed in #165 and will be included in the next release.

**Comment by dmcollom** [comment]
As of 0.8.0, this functionality has been added.
