### ISSUE TITLE
ReducedDatum ingest Python vs JSON gotcha

### ISSUE THREAD

**Issue by rachel3834** [TOMToolkit/tom_base#159]
I just hit a gotcha that I think is worth highlighting in the documentation/workshop.  Apologies if it is already but I didn't see it.  

In my lightcurve ingest code I had:

datum_params = {"target": target,
                              "data_product": dataset['product'],
                              "data_type": "photometry",
                              "source_name": dataset['product_id'],
                              "source_location": key,
                              "timestamp": date_obs,
                              "value": {"magnitude": entry['calibrated_mag'],
                        "magnitude_error": entry['calibrated_mag_err'],
                        "hjd": entry['hjd'],
                        "filter": dataset['dataset_code'].split('_')[-1]}
                              }
                            
datum = ReducedDatum.objects.create(**datum_params)

...which seemed to work fine, new ReducedDatum objects created in the TOM with the right values etc.  

But then when I tried to go to the TargetDetailView for this Target, the TOM crashed with this error:
                
Request Method: | GET
-- | --
http://127.0.0.1:8000/targets/44209/
2.2.4
JSONDecodeError
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py in raw_decode, line 353
/Users/rstreet/software/tom_venv3_brew/bin/python
3.7.0
['/Users/rstreet/software/romerea_phot_tom',  '/Users/rstreet/software/tom_venv3_brew/lib/python37.zip',  '/Users/rstreet/software/tom_venv3_brew/lib/python3.7',  '/Users/rstreet/software/tom_venv3_brew/lib/python3.7/lib-dynload',  '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7',  '/Users/rstreet/software/tom_venv3_brew/lib/python3.7/site-packages',  '/Users/rstreet/software/tom_venv3_brew/lib/python3.7/site-packages/pyLIMA-0.1.5-py3.7.egg',  '/Users/rstreet/software/tom_venv3_brew/lib/python3.7/site-packages/emcee-3.0rc2-py3.7.egg',  '/Users/rstreet/software/tom_venv3_brew/lib/python3.7/site-packages/pyDANDIA-0.1-py3.7-macosx-10.9-x86_64.egg',  '/Users/rstreet/software/tom_venv3_brew/lib/python3.7/site-packages']

Although I had JSON-friendly double-quotes in the value parameter dictionary, this was getting parsed into Python single-quotes somewhere along the line and broke the view. 

One solution is to force the entry in the value parameter to be a JSON object when the ReducedDatum is created:
value = {"magnitude": entry['calibrated_mag'],
                        "magnitude_error": entry['calibrated_mag_err'],
                        "hjd": entry['hjd'],
                        "filter": dataset['dataset_code'].split('_')[-1]}
                                    
datum_params = {"target": target,
                              "data_product": dataset['product'],
                              "data_type": "photometry",
                              "source_name": dataset['product_id'],
                              "source_location": key,
                              "timestamp": date_obs,
                              "value": json.dumps(value),
                              }

...something for users like me (who didn't realise JSON was quite that picky about quotes) to beware of.

**Comment by dmcollom** [comment]
So I finally went ahead and replicated this in my TOM, and it looks like the ORM represents the value as a dict on the model (which makes sense, as it went in that way) despite it being a TextField. When data is ingested through the TOM workflow, it's converted into a string before being saved, and `json.loads` is called on the value for photometry plotting, hence the error.

I don't know what documentation there necessarily needs to be as far as ensuring only strings are stored in TextFields, but I suppose we can put a caveat in the API doc.

**Comment by dmcollom** [comment]
@rachel3834 At some point since this issue I added the following [here](https://tom-toolkit.readthedocs.io/en/stable/api/tom_dataproducts/models.html):

> It should be noted that when storing a dict in a ReducedDatum value field, it should always be converted with json.dumps before saving, as certain functions in the TOM Toolkit call json.loads with ReducedDatum value fields.

Is this sufficient? It's not terribly prominent, but anyone accessing the model in a programmatic fashion should really be looking at the docs.
