### ISSUE TITLE
Anonymous users can see user list

### ISSUE THREAD

**Issue by zemogle** [TOMToolkit/tom_base#168]
If you're not logged in, you can still see the user list including email addresses. I suggest making this list only visible to PIs.

**Comment by dmcollom** [comment]
I agree that anonymous users absolutely should not be able to see the user list, and have submitted PR #171 to that effect. I think we can stop at allowing only logged-in users to see the list, however--larger TOMs that want to restrict it to PIs only can easily do so by extending that view and inheriting from the SuperuserRequiredMixin.

**Comment by dmcollom** [comment]
This has been corrected in release 0.8.0.
