### ISSUE TITLE
Missing coordinate hints in target creation form

### ISSUE THREAD

**Issue by hombit** [TOMToolkit/tom_base#197]
When filling form `/targets/create/` it is not obvious that default units of Right Ascension are hours. Please add hints described how Right Ascension and Declination can be specified with some examples, e.g. `18h30m30s` or `-30d57m15s`. Also it is not clear what particular equatorial coordinate system is used.

**Comment by dmcollom** [comment]
This has been addressed in PR #214 and has been released in 1.2.0.
