### ISSUE TITLE
Importing Photometry should support different date formats

### ISSUE THREAD

**Issue by jnation3406** [TOMToolkit/tom_base#199]
It looks like importing Photometry files expects iso formatted dates, but it would be useful if it could also support julian dates or modified julian dates, as a lot of data is stored in this format

**Comment by dmcollom** [comment]
Do you have the file you sent that was rejected? It's currently configured to accept mjd.

**Comment by jnation3406** [comment]
No I was working with another attendee at the time. I think it was a properly formatted file, and the dates were just in mjd instead of iso format. I believe it was 'accepted' because the photometry tab had a plot in it afterwards, but the x-axis of that plot looked like raw mjd numbers. I think it would probably be more usable to have the plot show human formatted dates on its axes, no matter what format the data was ingested in.

**Comment by dmcollom** [comment]
Closing this as it was never reproducible and it has never been reported since.
