### ISSUE TITLE
API Documentation is missing for some generic classes

### ISSUE THREAD

**Issue by jnation3406** [TOMToolkit/tom_base#200]
There are some API Documentation pages that are missing useful information. 
For example for the Alert Broker Base: https://tom-toolkit.readthedocs.io/en/latest/api/tom_alerts/brokers.html#module-tom_alerts.alerts - it should at least list the abstract methods that need to be implemented and what they are expected to take in and return. 

The Base Harvester Class page is also missing any useful information.

**Comment by dmcollom** [comment]
This has been addressed and is corrected as of release 1.2.0.
