### ISSUE TITLE
TemplateTag for Most Recently Updated Targets

### ISSUE THREAD

**Issue by dmcollom** [TOMToolkit/tom_base#204]
**Is your feature request related to a problem? Please describe.**
As per Andy Howell: "Landing page: I like having 'latest targets' and 'latest comments' on the landing page.  Can we also have 'most recently updated targets?'"

**Describe the solution you'd like**
A widget displaying which targets have changed in the same vein as the latest targets widget.

**Comment by blancmatter** [comment]
Just to clarify the desired functionality, I'm reading into the solution as;

"A widget displaying a list of targets for which related Observations, Data Products or Reduced data has most recently changed"

Is this correct? I had a little go and have implemented by most recently changed in the Target model only, but can extend to the above description (perhaps!)

**Comment by dmcollom** [comment]
Yes, Andy wasn't explicit but I think that's a fair interpretation. I presume that a user would want to know when any related aspects of a target are modified, as I can't imagine actual target attributes will change with the frequency that would make it useful to know about it.

**Comment by dmcollom** [comment]
Released in 1.5.0.
