### ISSUE TITLE
Unauthorized users attempting to access privileged content continually loop to login screen 

### ISSUE THREAD

**Issue by dmcollom** [TOMToolkit/tom_base#230]
**Describe the bug**
In Lukasz's TOM, new users can view all Targets in the TargetListView, but for whatever reason cannot access the TargetDetailView.

Additionally, despite the user lacking the correct permissions, attempting to login redirects to another login screen, rather than something indicating a 403.

**Comment by dmcollom** [comment]
This wound up being an unusual case in that the superuser was not a member of the public group, which should have happened during the setup script. However, we should still use this to track the redirection issue for unauthorized users.

**Comment by Fingel** [comment]
Fixed in https://github.com/TOMToolkit/tom_base/commit/0185d07f224bfaab5aeab630e18ec985dbcea493
