### ISSUE TITLE
Python 3.6.9 : Catalog search crash on fresh install

### ISSUE THREAD

**Issue by ebachelet** [TOMToolkit/tom_base#233]
**Describe the bug**
I have a fresh install of the TOM **under python 3.6.9**, everything seems to worked smoothly. But when I click on catalog seearch, it is crashing.

**To Reproduce**
1. Go to 'Home'
2. Click on 'Catalog Search'

**Expected behavior**
I would expect to see the page.

**Screenshots**
![image](https://user-images.githubusercontent.com/14871821/70760276-0d36db00-1d41-11ea-921a-50b388538ee4.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser Firefox
 - Version 71
 - Python Version 3.6.9

**Comment by dmcollom** [comment]
Hi @ebachelet,

Can you give some information about what you were searching for and what catalog you were using? Can you give us the same search terms you used?

**Comment by ebachelet** [comment]
Hi @dmcollom 

I did not have time to search anything, I just clicked on the button and it crashed. I was hoping to harvest some Gaia events

**Comment by Fingel** [comment]
I am also unable to reproduce this issue. But looking at the stack trace, it does not appear you are using a virtual environment. We highly encourage using one, and realistically can't support installs that don't use one.
