### ISSUE TITLE
New extra fields default not shown if target previously exist

### ISSUE THREAD

**Issue by ebachelet** [TOMToolkit/tom_base#240]
The default extra fields are not shown if the target was created previously without.

**To Reproduce**
1. Create a target
2. Create later some extra fields
3. Extra fields not sidplayed on the target page

**Desktop (please complete the following information):**
 - OS:Ubuntu 18
 - Firefox
 - Python 3.6.9

**Comment by dmcollom** [comment]
This was addressed by #259 and was released in 1.3.1.
