### ISSUE TITLE
Eccentricity and Epochs not filled when creating new target with JPL Catalog Search 

### ISSUE THREAD

**Issue by fraserw** [TOMToolkit/tom_base#241]
**Description:**
When using the Catalog search of JPL Horizons to create a new target, some critical fields remain unpopulated. These fields include eccentricity, epoch of perihelion, and epoch of elements, at the very least. Orbital element scheme is also unfilled, as are all element errors. 

**To Reproduce:**
From the targets menu, select targets. 

Select create targets -> catalog search

Enter "Eris" in the Term field, and select JPL horizons.

The returned form will be mostly field, with the exception of the outstanding entried mentioned above.

**Expected behavior**
At the very least, eccentricity and epoch of elements need be filled for the elements to be complete and valid. 

**Desktop (please complete the following information):**
Error occurs in OSX, 10.14.x
Chrome and firefox
version 1.2.4
python 3.7

**Comment by fraserw** [comment]
I have made some progress on this.

The full missing fields are eccentricity, epoch of perihelion, epoch of elements, and the scheme.

The following four lines added to jplhorizons.py at line 37:

>>>        target.eccentricity = self.catalog_data['e'][0]
>>>        target.epoch_of_perihelion = self.catalog_data['Tp_jd'][0]
>>>        target.epoch = (self.catalog_data['datetime_jd'][0]-2415020.50000)/365.0 + 1900.  #referenced to 1900 for convenience
>>>        target.scheme = 'MPC_MINOR_PLANET'

 at least allow an object to be created equally.

But in scheduling an observation, an error is thrown along the lines of:

"epochofel: Ensure this value is greater than or equal to 10000."

I wondered if the epoch of elements was mislabelled, requiring JD days (which is normal) compared to JD years (which is unusual) on the target creation page. So I replaced the target.epoch=... line with the simple JD, and the error changes to:

"epochofel: Ensure this value is less than or equal to 100000."

This suggests to me that target.epoch should be days, in which case the epoch zero JD is needed to fix this bug.

**Comment by fraserw** [comment]
I see from dmcollom changes that the same fix was already proposed. Those proposed changes will not address the above issue with requiring that the epoch of elements be a value between 10000 and 100000.

Also, the target.scheme should be automatically set to MPC_MINOR_PLANET

**Comment by dmcollom** [comment]
@fraserw Yup, I talked with LCO's own Tim Lister and he helped me reconcile our fields with JPL. That said, you bring up a couple of very salient points.

- Scheme is a toughie, because things can come back from JPL that fit into the JPL_MAJOR_PLANET scheme (which is ultimately just for LCO observing anyway). Are you aware of a reliable way based on what JPL returns to populate scheme? If not, I think it just needs to be left as an exercise for the reader, so to speak.

- The reason for the observing bug is that we're overloading epoch with epoch of elements. Either we (the TOM Toolkit developers) can leave it this way and route it to the correct field based on scheme when submitting observations, or we can split the fields, which feels like the safer option.

Happy to hear opinions, but I personally think scheme should be left alone, and the fields should be split, which I'll do shortly.

**Comment by fraserw** [comment]
As far as I know, the orbital elements for a planet and for a minor body are exactly the same. But that doesn't matter much, as use the JPL Horizons catalog search to pull out the planets - Searching for "Jupiter" for example raises an error. And searching for 599 (Jupiter Body) brings in asteroid 599, and @599 (also jupiter reference) raises an error.

AFAICT there is no possible scenario in which a user searches with the JPL Horizons interface provided by TOMs, and is able to get back a planet. That is, with the search provided, the elements are *always* in JPL Minor body form.

Similarly, AFAICT the MPC searches cannot return the planets either. Searching for Jupiter there raises an error. Again there, it seems that only minor bodies are returned. (I should note that it appears the MPC search is also broken as it will not succeed in searching for comets. I'll create another issue)


As for the epoch date issue, this is not solved. The range allowed by TOMs is 10K to 100K, which is non-sensical for either a JD or a JD in years. Values in those ranges would only be valid if in days past some reference date within the last 100 years (like the Dublin Julian Date, for example).

**Comment by dmcollom** [comment]
> AFAICT there is no possible scenario in which a user searches with the JPL Horizons interface provided by TOMs, and is able to get back a planet.

This is extremely useful, and simplifies things greatly. In my change, I'll ensure that all objects returned by the JPL harvester are given the MPC_MINOR_PLANET scheme.

> I should note that it appears the MPC search is also broken as it will not succeed in searching for comets.

I believe you are correct on this. I'll make sure to fix this in a separate PR.

> As for the epoch date issue, this is not solved.

I think this is something that we as naive software people didn't consider. The LCO observation portal (where the error is propagating from) expects MJD, and JPL returns the epoch of elements in JD. As the TOM doesn't do anything to modify this in between the data ingestion and the observation submission, the error pops up.

I'll update it to simply store the value from JPL as is, and then do the conversion to MJD during observation submission if the epoch of elements that's being submitted is >100000.

**Comment by fraserw** [comment]
Ahhh that explains it - MJD vs JD. 

Can one not just subtract 2400000.5 from the JD when storing it? That is, right in the jpl harvester?

**Comment by dmcollom** [comment]
Yup, and that's the plan. It isn't the only harvester that brings back JD, so I'll need to correct it for more than one. Should be released some time tomorrow.

**Comment by fraserw** [comment]
Fantastic. Thanks @dmcollom 

Might I recommend the value 417700, which roughly corresponds to the year 3000. I have had need for suh high numbers in past simulations. NOt sure I would need them in TOMs, but I could stretch.

**Comment by dmcollom** [comment]
The TOM Toolkit actually doesn't restrict the limit on the epoch of elements--the error you're seeing is from the LCO Observation Portal. Given that the LCO observation portal submits real observations, I believe 100000 was considered just an arbitrary reasonable limit.

I will keep that in mind if I end up writing any TOM Toolkit utility that might need a hard limit, though!

**Comment by dmcollom** [comment]
Just released 1.2.5 which should address the problem. Let me know if you experience any more issues after upgrading. Thanks for the feedback! There may be some growing pains on the non-sidereal side of the TOM, but as long as you let us know, we'll make the corrections as quickly as possible.
