### ISSUE TITLE
Astropy 4.0 required

### ISSUE THREAD

**Issue by mpgh** [TOMToolkit/tom_base#252]
During the installation on a system with an older astropy version, some packages require astropy 4.0 which could be added to the requirements.txt

More specifically the following version is incompatible:

ERROR: gwcs 0.12.0 has requirement astropy>=4.0, but you'll have astropy 3.2.2 which is incompatible.
ERROR: specutils 0.7 has requirement astropy>=4.0, but you'll have astropy 3.2.2 which is incompatible.

**Desktop (please complete the following information):**
 - OS: Linux
 - Python Version 3.7.4

**Comment by dmcollom** [comment]
This has been addressed in #258 and is in release 1.3.1. Thanks for bringing this to our attention, @mpgh!
