### ISSUE TITLE
Every broker should show a link to documentation

### ISSUE THREAD

**Issue by TimotheeGr** [TOMToolkit/tom_base#271]
I am using several of the brokers available and I have to search for the name of each broker on internet to know more about it.

It would be easier if every broker had a link toward the webpage of the broker or some documentation, like what the MARS broker does:
![Capture d’écran de 2020-04-15 18-07-44](https://user-images.githubusercontent.com/51410054/79393928-4f1c9b80-7f44-11ea-9730-4fd828a634e2.png)

**Comment by jchate6** [comment]
I believe this is done now, but will add it to the Broker Audit (Issue #640 ) as a thing to check for.
