### ISSUE TITLE
Admin should not be able to delete AnonymousUser

### ISSUE THREAD

**Issue by TimotheeGr** [TOMToolkit/tom_base#272]
I recently deleted by mistake the AnonymousUser then I could not see any page without being logged in.

It was quickly solved by a `./manage.py migrate` but still it would be better if AnonymousUser was hidden from the Users page I suppose.
(Or maybe it has a use I don't know about...)

**Comment by dmcollom** [comment]
Hi @TimotheeGr,

Appreciate you bringing this up! I think we can all agree that it's a little confusing to arbitrarily have a user that wasn't explicitly created. I'm adding a description of what `AnonymousUser` is to the FAQ, along with a sentence describing the implications of removing it. It'll be in the documentation after the next release.

The AnonymousUser is created by our AuthN/AuthZ library (django-guardian) to allow unauthenticated users to view public pages--which should explain why deleting AnonymousUser caused the problem that it did for you.

Now, to your point--while the user was visible from the page, the list of users is only visible to a PI (who is also a Django admin), so I don't think it's an inherent problem. If the user were hidden away and only visible in the Django admin interface, then there's a security risk if the PI is unaware of the AnonymousUser. I think the lessons here are that with great power comes great responsibility, and that we need to update our documentation, but that the code should probably stay as is.
