### ISSUE TITLE
Django migrations no longer updating

### ISSUE THREAD

**Issue by jlibermann** [TOMToolkit/tom_base#294]
**Describe the bug**
Hi, sorry to bother you again but I'm having an issue with new migrations in my Django project. I made changes to some of the models in `tom_observations` and `tom_targets`, but I realized these changes are not being detected when I run `makemigrations`. The issue may be a naming conflict, as I have `tom_observations` and `tom_targets` folders in both my project root and in `venv/lib/python3.8/site-packages`. Editing the models from within the `site-packages` directory seems to apply my changes to the database but this is not ideal. I was wondering if there is an easy way to override the existing `models.py` files for `tom_observations` and `tom_targets` from within my project root?
**To Reproduce**
1. Add fields to `models.py` file in `Documents/panoptes-tom/panoptes_tom/tom_observations`.
2. Run `./manage.py makemigrations`
3. See `No changes detected`

**Expected behavior**
I expected my new fields to be created in the database after running migrations.

**Desktop (please complete the following information):**
- OS: [Ubuntu 20.04]
- Python Version [e.g. 3.8.3]

**Comment by rachel3834** [comment]
Hi there, thanks for posting this issue.  We'd like to help you find the best way to implement the parameters you need, but we think the best way would be to talk this over with you.  Do you have time for a Zoom call with our team?  You can reach me at rstreet@lco.global to organize that.

**Comment by jlibermann** [comment]
Thanks for working through this issue with me!
