### ISSUE TITLE
Django version needs to be pinned more specifically--3.1 is incompatible with pinned version of django-filter

### ISSUE THREAD

**Issue by dmcollom** [TOMToolkit/tom_base#295]
`setup.py` specifies `django>=3.0.7`, which installs `3.1`. However, `django-filter` is pinned at `2.2.0`, which is incompatible with Django 3.1. We'll need to either bring `django-filter` up to `2.3`, or pin Django to `3.0.7`.

We should also take this opportunity to install dependabot to avoid issues like this in the future.

**Comment by phycodurus** [comment]
release [1.7.4](https://github.com/TOMToolkit/tom_base/releases/tag/1.7.4) pins `django==3.0.7`
