### ISSUE TITLE
Observatory sites indistinguishable on target visibility plot

### ISSUE THREAD

**Issue by rachel3834** [TOMToolkit/tom_base#296]
**Describe the bug**
When I select a target, and try to plan observations using the "observe" tab, the resulting plot of target airmass should have a labeled y-axis.  It would also be good to use different line types to help users distinguish between the different observatories, as otherwise the red and orange solid lines are quite hard to tell apart.  The mouseover tips are helpful, but could be problematic for those who are color-blind. 

**To Reproduce**
1. Select a target
2. Click on observe tab
3. Click either the LCO or GEM buttons
4. Resulting plot shows issue

**Expected behavior**
Plot should have a y-axis label for clarity
Plot should use dotted or dashed lines to distinguish LCO from Gemini sites

**Desktop (please complete the following information):**
- OS macOS Catalina
- Chrome v83.0.4103.116

**Comment by dmcollom** [comment]
A variant of this exists that I accidentally merged into main:

![image](https://user-images.githubusercontent.com/1599514/102660172-765ce580-412f-11eb-82ed-43dd00183616.png)

It's even more clear if one zooms in:

![image](https://user-images.githubusercontent.com/1599514/102660215-85dc2e80-412f-11eb-9a8d-93ab55fbdaa4.png)

@rachel3834 Do you think this is sufficient?

**Comment by rachel3834** [comment]
Thanks!  The different plot symbols are a great help.
