### ISSUE TITLE
Link comments to the targets they are associated with

### ISSUE THREAD

**Issue by rachel3834** [TOMToolkit/tom_base#297]
**Describe the bug**
When a user posts a comment to a target page, there is a default feature which summarizes these comments on the TOM's landing page.  This would be very useful but currently the comments cannot easily be traced back to the originating target, so the comments are without context.  

**To Reproduce**
1. Go to a target page
2. Post a comment in the comment box
3. Go to the TOM landing page
4. See comment in the "latest comments" box

**Expected behavior**
The entries in the latest comments box should indicate which target they refer to (displaying only comments for targets that the user has permission to access).  Clicking on a comment should take you to the target page for that comment.  

**Desktop (please complete the following information):**
- OS MacOS catalina
- Chrome

**Comment by dmcollom** [comment]
This was addressed in 1.8.0.
