### ISSUE TITLE
Docs on plugins should link to their Github repos

### ISSUE THREAD

**Issue by rachel3834** [TOMToolkit/tom_base#318]
**Describe the bug**
Reading the [documentation](https://tom-toolkit.readthedocs.io/en/stable/api/plugins.html#tom-toolkit-plugins) for available TOM plugins, a plugin for the Liverpool Telescope is mentioned but no link is given.  To make it easy for the user, it should link here: https://github.com/TOMToolkit/tom_lt

**Comment by dmcollom** [comment]
This has been addressed and will be included in the next release.
