### ISSUE TITLE
Full set of orbital elements should not be required for new non sidereal targets

### ISSUE THREAD

**Issue by Fingel** [TOMToolkit/tom_base#34]
When inputting new targets, the full orbital elements are often not known, thus they should not be required.

Non sidereal projects will probably need additional custom fields to add to their targets. This is up for further discussion.

**Comment by zemogle** [comment]
Not sure if this is related but on submitting a non-sidereal target you have to complete all target  fields (including all the `name` fields). There are a core fields which are common to all types of (natural) moving target. Maybe these could be the ones which are required?

Required for all:
-  schema
-  epochofel
-  orbinc
-  longascnode
-  argofperih
-  eccentricity

Comets:
- perihdist
- epochofperih

Asteroids:
- dailymotion
- meananom
- meandist

**Comment by zemogle** [comment]
Currently the non-siderial functionality for comets will not work because `peridist` is missing from the input form and so targets will fail validation on submit.

**Comment by zemogle** [comment]
This issue is currently being looked at by @joesingo

**Comment by dmcollom** [comment]
This was addressed by #179 back in October.
