### ISSUE TITLE
Avoid negative exposure times in observation request forms

### ISSUE THREAD

**Issue by rachel3834** [TOMToolkit/tom_base#349]
**Describe the bug**
The observing request form for LCO Photometric Sequence allows negative integers for the exposure time, number of exposures and block number, none of which are valid.  It's surprisingly easy for users of the browser interface to accidently click the down arrow and get a negative value without noticing.  

**To Reproduce**
1. Under the Observe tab for a Target, go to the LCO observation button 
2. Click on Photometric Sequence
3. Use the arrows to set the value of e.g. exposure time
4. Negative values are allowed.  

**Expected behavior**
Allow positive integers only.  

**Desktop (please complete the following information):**
- Mac OS Catalina 10.15.6
- Chrome
- Python 3.7.4

**Comment by dmcollom** [comment]
This has been fixed in 2.1.1.
