### ISSUE TITLE
Django SynchronousOnlyOperation Error when scripting TOM with Jupyter notebook 

### ISSUE THREAD

**Issue by lchjoel1031** [TOMToolkit/tom_base#351]
**Describe the bug**
Ran into an error of "SynchronousOnlyOperation: You cannot call this from an async context - use a thread or sync_to_async." when scripting TOM with Jupyter notebook. More specifically, it happens when I tried to create a target with "t = Target.objects.create(name='m51', type='SIDEREAL', ra=123.3, dec=23.3)"

**To Reproduce**
1. launch the notebook server with "./manage.py shell_plus --notebook"
2. create a new notebook with Django Shell-Plus option
3. in a new cell, type in "from tom_targets.models import Target"
4. type in "t = Target.objects.create(name='m51', type='SIDEREAL', ra=123.3, dec=23.3)"
5. run the cell and see error

**Expected behavior**
Target post save hook: Messier 51 created: True
[Untitled.pdf](https://github.com/TOMToolkit/tom_base/files/5344467/Untitled.pdf)

**Screenshots**

Please see the attached PDF file.

**Desktop (please complete the following information):**
- OS: macOS High Sierra 10.13.6
- Browser: safari
- Version: 13.1
- Python Version: 3.7.7

**Additional context**
It might be a Django 3 issue.

**Comment by dmcollom** [comment]
This does appear to be a Django 3 problem. According to the [async safety section of the documentation](https://docs.djangoproject.com/en/3.1/topics/async/#async-safety), you can set the appropriate environment variable to allow the code to run. Take a look for the specifics.

There are adapter functions to run synchronous code in asychronous contexts, but Django specifically points out that they don't work for Jupyter notebooks (and just to be safe, I tried and failed as well).
