### ISSUE TITLE
Lasair broker filter parameters appear to be required but indicate they are optional

### ISSUE THREAD

**Issue by rachel3834** [TOMToolkit/tom_base#374]
**Describe the bug**
When I tried to create a filter for the Lasair broker, the form indicates that only the query name and the object name are required parameters.   However, when I run the filter without coordinates, it produces an 'NoneType' object is not an iterator error.  If I add coordinates and a radius, I get the error below - perhaps because I didn't include any JSON in the form submission?

**To Reproduce**
1. On an out-of-the-box TOM, go to Alerts -> Lasair
2. Complete the form fields which indicate the values are required, but not the remaining fields
3. Click save, then try to run the filter. 

**Expected behavior**
If the search coordinates, radius and JSON fields are required, then these parameters should have stars indicating that this is the case.  

**Desktop (please complete the following information):**
- OS: Mac OSx Catalina 10.15.7
- Browser Chrome

**Additional context**
Diagnostic output below:

Request Method: | GET
-- | --
http://127.0.0.1:8000/alerts/query/2/run/
3.1.1
JSONDecodeError
Expecting value: line 2 column 1 (char 1)
/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py, line 355, in raw_decode
/Users/rstreet1/software/tom_venv/bin/python
3.7.4
['/Users/rstreet1/software/demo_tom',  '/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python37.zip',  '/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7',  '/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload',  '/Users/rstreet1/software/tom_venv/lib/python3.7/site-packages',  '/Users/rstreet1/software/tom_venv/lib/python3.7/site-packages/matplotlib-3.3.0-py3.7-macosx-10.14-x86_64.egg',  '/Users/rstreet1/software/tom_venv/lib/python3.7/site-packages/pyparsing-3.0.0a2-py3.7.egg',  '/Users/rstreet1/software/tom_venv/lib/python3.7/site-packages/kiwisolver-1.2.0-py3.7-macosx-10.14-x86_64.egg',  '/Users/rstreet1/software/tom_venv/lib/python3.7/site-packages/cycler-0.10.0-py3.7.egg',  '/Users/rstreet1/software/tom_venv/lib/python3.7/site-packages/IPython/extensions']
Tue, 03 Nov 2020 20:14:11 +0000

**Comment by dmcollom** [comment]
Fixed in #380
