### ISSUE TITLE
Data menu shouldn't crash TOM

### ISSUE THREAD

**Issue by rachel3834** [TOMToolkit/tom_base#375]
**Describe the bug**
Clicking on the "Data" option in the main nav bar of an out-of-the-box TOM causes the TOM to crash.

**Expected behavior**
Going to /dataproducts/data/ should produce a simple page reporting that there are no suitable data products to be displayed.  In this example, the TOM has some observation data products and some ReducedDatums stored. 

**Desktop (please complete the following information):**
- OS: OSx Catalina 10.15.7
- Browser  Chrome

**Additional context**
Error output here:

Request Method: | GET
-- | --
http://127.0.0.1:8000/dataproducts/data/
3.1.1
ValueError
slice step cannot be zero
/Users/rstreet1/software/tom_venv/lib/python3.7/site-packages/fits2image/scaling.py, line 115, in extract_samples
/Users/rstreet1/software/tom_venv/bin/python
3.7.4
['/Users/rstreet1/software/demo_tom',  '/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python37.zip',  '/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7',  '/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload',  '/Users/rstreet1/software/tom_venv/lib/python3.7/site-packages',  '/Users/rstreet1/software/tom_venv/lib/python3.7/site-packages/matplotlib-3.3.0-py3.7-macosx-10.14-x86_64.egg',  '/Users/rstreet1/software/tom_venv/lib/python3.7/site-packages/pyparsing-3.0.0a2-py3.7.egg',  '/Users/rstreet1/software/tom_venv/lib/python3.7/site-packages/kiwisolver-1.2.0-py3.7-macosx-10.14-x86_64.egg',  '/Users/rstreet1/software/tom_venv/lib/python3.7/site-packages/cycler-0.10.0-py3.7.egg',  '/Users/rstreet1/software/tom_venv/lib/python3.7/site-packages/IPython/extensions']
Tue, 03 Nov 2020 20:53:00 +0000

**Comment by dmcollom** [comment]
This has been fixed in 2.6.8.
