### ISSUE TITLE
LCO Observation module requires additional paramteres for non sidereal targets.

### ISSUE THREAD

**Issue by Fingel** [TOMToolkit/tom_base#39]
Currently trying to submit an observation of a non sidereal target to LCO return an error that the following required parameters are missing:

epochofel
eccentricity
scheme

These need to be parameters on the TOM target or passed through in the observation form.

**Comment by zemogle** [comment]
These fields are missing from:

https://github.com/TOMToolkit/tom_base/blob/99442b027f864a5cad1e6be0e098fd0f9fdc4a4c/tom_targets/models.py#L18

There are different schemes for non-sidereal solar system targets. Valhalla uses 3 different types `JPL_HORIZONS`, `MPC_MINOR_PLANET` and `MPC_COMET`, each with different required fields.

**Comment by Fingel** [comment]
I think @dmcollom fixed this recently? Please close if so.
