### ISSUE TITLE
When updateing observation status, maintain the current view

### ISSUE THREAD

**Issue by blancmatter** [TOMToolkit/tom_base#427]
**Description**

When clicking the `update observation status` in both the Observations Tab of the Target page or the Observations page, two elements happen that are mildly annoying.

* On the Target page, the default target page reopens and you have to reselect the Observations Tab
* On the Observations page, any filters which have been applied are immediately lost and all observations are displayed.

**Describe the solution you'd like**
When the `update observations status` button is clicked on both of these pages, the page reloads with exactly the same view after the process has been completed.

**Comment by dmcollom** [comment]
Addressed in #436 and released in 2.5.3.
