### ISSUE TITLE
Add support for a new broker: Fink

### ISSUE THREAD

**Issue by JulienPeloton** [TOMToolkit/tom_base#435]
**Is your feature request related to a problem? Please describe.**

I would like to add support for a new broker, Fink (https://fink-broker.org/). There is no problem for me to implement it, but I would like to know what's the best place to host it. 

I'm a bit confused whether the new TOM Toolkit Alert Broker Module should be 

1. a standalone repository (as is https://github.com/TOMToolkit/tom_antares for example), or 
2. a new module at `tom_base.tom_alerts.brokers` (https://github.com/TOMToolkit/tom_base/tree/main/tom_alerts/brokers), or 
3. a new module at `tom_alerts_dash.tom_alerts_dash` (https://github.com/TOMToolkit/tom_alerts_dash/tree/main/tom_alerts_dash), or 
4. something else. 

Any suggestions? Thanks!

**Comment by dmcollom** [comment]
I was unaware of the Fink broker--this is really impressive! It'd be great to get this into the TOM Toolkit.

In your case, it would either be option 1 or option 2. Option 3, the `tom_alerts_dash` repository, is for brokers that leverage our Dash interface for a more responsive experience in the TOM Toolkit, which is something that Fink could certainly do, but would require a basic broker module first.

We prefer brokers that are primarily maintained by other groups to be in standalone repos. It's up to you if you want it under the TOM Toolkit organization (which we would obviously really appreciate!) or as a standalone in your own organization. I've gone ahead and created [tom_fink](https://github.com/TOMToolkit/tom_fink), which could be transferred if you'd like it elsewhere, and invited you as a maintainer. Let me know how I can help!

**Comment by JulienPeloton** [comment]
Thanks @dmcollom for your answer, this is all clear! I've accepted the invitation to the tom_fink repository, and I will start from here.

**Comment by dmcollom** [comment]
Awesome! I'll close this out, and I suppose if you have any questions or need any support, just open up an issue in that repo, or ping me on the Slack workspace! Looks like you're not in it, but you can join here if you'd like: https://tom-toolkit-invite.lco.global/
