### ISSUE TITLE
Fink broker: adding a default button in the alert page

### ISSUE THREAD

**Issue by JulienPeloton** [TOMToolkit/tom_base#440]
**Is your feature request related to a problem? Please describe.**

The [tom-fink](https://github.com/TOMToolkit/tom_fink) module is now operational (version 0.2). I would like to add in the tom_base a dummy Fink module so that a button can be shown for demonstration purposes, with a text linking to [installation instructions](https://github.com/TOMToolkit/tom_fink#how-to-use-the-fink-module-inside-your-tom).

If this makes sense to you, I would be happy to open the corresponding PR (taking inspiration from the [SCIMMA](https://github.com/TOMToolkit/tom_base/blob/main/tom_alerts/brokers/scimma.py) example).

**Comment by dmcollom** [comment]
Yes, go ahead and make that PR. Very exciting to have this, nice work!

**Comment by JulienPeloton** [comment]
Thanks for merging! #441
