### ISSUE TITLE
manage.py runcadencestrategies doesn't advance the window

### ISSUE THREAD

**Issue by griffin-h** [TOMToolkit/tom_base#447]
**Describe the bug**
After a successful observation, `manage.py runcadencestrategies` doesn't advance the window for the next observation request because `start = now` and `end = now + cadence_frequency` are hardcoded into the `LCOPhotometricSequenceForm` and `LCOSpectroscopicSequenceForm`. This hardcoding does make sense for requests submitted via the web form, but when the form is used by the management command, it needs to be able to set an arbitrary start and end time.

**To Reproduce**
1. Have an `ObservationRecord` in your database that uses a cadence strategy, and where the last observation succeeded.
2. Run `manage.py runcadencestrategies`
3. See that your TOM requested an observation with a window starting right now.

**Expected behavior**
The next observation in the sequence should start some number of days in the future, according to your `cadence_frequency`.

**Desktop (please complete the following information):**
- OS: macOS 11.2.3
- Browser: Safari
- Version: 14.0.3
- Python Version: 3.7.3

**Comment by dmcollom** [comment]
Well-spotted--this should be a relatively easy fix once we have time to fix/test it (which might be a little while). Basically, `clean` should only set `start` and `end` if they don't come through in `cleaned_data`. You're welcome to take this on if you'd like, otherwise I might be able to do it by end of the week (no guarantees, though).

**Comment by griffin-h** [comment]
I did make a quick attempt before opening the issue, but I couldn’t get it
to work. I think the inheritance of all the form classes was throwing me
off.

**Comment by dmcollom** [comment]
Well, I went ahead and made the change, but I think you're better positioned to test this than I am. I just released `2.6.3a1`, if you wouldn't mind trying it out.

**Comment by dmcollom** [comment]
The fix for this was released in ``2.6.6``.
