### ISSUE TITLE
TOM listening to filtered streams from brokers, rather than sending queries to their DB

### ISSUE THREAD

**Issue by johannct** [TOMToolkit/tom_base#450]
**Is your feature request related to a problem? Please describe.**
In the context of DESC, we are brainstorming about how we will use a marshall/tom to aggregate information from the community brokers that will be hooked to the Rubin streams. One of the present elements of brainstorming is whether we need to listen to filtered streams or whether we just need to query the brokers' DB on a regular basis.

**Describe the solution you'd like**
I am aware of DB queries and their automation in TOM-TOOLKIT with cron jobs, but I do not see any mention of consuming filtered streams within the tom. Is it at all possible?

**Additional context**
None beyond the above

**Comment by rachel3834** [comment]
Thanks for getting in touch Johann.  We already have experience with handling alert streams, based on our MARS broker, and we have also considered the value in adding the capability to consume a filtered stream to the Toolkit.  That part is relatively straightforward.  What we would be interested to learn from DESC is more about your use-case and workflow - for example, do you want to add all received alerts as targets in the TOM?  Is there any cross-matching or selection carried out?  What display tools would be most suitable for your workflow?  We would be happy to work with you to describe this in more detail, and factor this into our development program.

**Comment by johannct** [comment]
Thanks for the fast response. Honestly our use case is not yet totally clear, and we are in stage of investigation of tools at our disposal and what we can make them do :) So in the context of the DESC broker challenge we want our marshall/Tom to retrieve the results of the challenge from all the brokers involved. This can be done from querying their DB or from receiving their filtered streams. For LSST operations, as you probably know DESC does not intend to have its own broker, but will definitely need to retrieve either the filtered streams it is interested in or to query their DB about once a day. We might see interest in being able to access filtered streams directly, depending among other things about the general infrastructure of the Rubin Data Facility at SLAC and how DESC interacts with it, with the prompt DB, etc.... @agkim may have a more expert idea about all this

**Comment by rachel3834** [comment]
It sounds like the best next step would be to work step by step through
your work flow to get a better idea of what you need from the alert
streams, where you expect to get them, how quickly you need them, whether
and how you need to compare the output from different brokers, and what
display and visualization tools you will need.  Hopefully our demos at the
workshop will have given you an overview of what we currently provide, and
we can design anything you feel is missing.
Perhaps I can arrange a good time to brainstorm with your team?

**Comment by johannct** [comment]
Sorry for the delay. Yes so with Alex we probably need to define our workflow better. The general idea is that the DESC marshall/TOM will aggregate brokered filtered streams, first in the context of our broker challenge to evaluate the situation wrt DESC science, and moving forward in the context of operations. We could do that just by cron-based querying of each broker's DB, but we also anticipate a need for direct filtered stream access for DES heavy duty algorithms like the RESSPECT recommending system.

**Comment by rachel3834** [comment]
The Toolkit already provides most if not all the tools necessary for a
cron-based query to multiple brokers, and we have experience with
processing direct alert streams thanks to our MARS broker, though we have
not yet provided the ability to ingest a direct alert stream in the base
Toolkit.  In principle, it would be reasonably straight forward to build a
TOM that receives a direct alert stream, creates targets as the alert
stream comes in and then you have APIs which would enable you to interface
with RESSPECT (or any other software) to generate recommendations, and
store output parameters and additional data products to the TOM where your
users could display them.

So please let us know how you would like to go about this.  We would be
happy to meet with you to talk this over when you feel you have a clear
idea of your desired workflow.

**Comment by dmcollom** [comment]
Yes, that `assign_perm` on line 83 is what you want--just make sure to also assign `tom_targets.change_target` and `tom_targets.delete_target` if you want your users to have those permissions as well.

**Comment by rachel3834** [comment]
@johannct Since this issue was created we have implemented a new tom_alertstreams module which enables users to directly receive Kafka streams to their TOM.  Does this address your needs?

**Comment by johannct** [comment]
I believe it would. Thanks. At any rate this issue is old and the code evolved on our side as well. So this can be closed.
