### ISSUE TITLE
Target ordering on target list page?

### ISSUE THREAD

**Issue by Fingel** [TOMToolkit/tom_base#481]
Hi,
I noticed that the default ordering for Targets is by id: https://github.com/TOMToolkit/tom_base/blob/c2a33e032e21a54fd877519a8755db4c9fab806f/tom_targets/models.py#L232
(also I think this line is redundant because it's the default behavior) additionally, the TargetListView does not set it's own ordering.  I don't find ordering by the database ID in anyway useful or meaningful, in fact it's the opposite of what I'd like the targets in my TOM to be ordered by: creation date. As in, it would be more useful to see the newest targets first instead of them being last.

Is there any way I can override this? I'm not seeing a way besides writing my own target list view, which would be less than ideal.

**Comment by dmcollom** [comment]
First of all, I would be remiss if I didn't do this: https://github.com/TOMToolkit/tom_base/blame/c2a33e032e21a54fd877519a8755db4c9fab806f/tom_targets/models.py#L232

But yes, wholeheartedly agree that it should be something of greater value, either name or creation date. We do something a little janky in the calibration-tom that appears to work for meta values as well:

https://github.com/LCOGT/calibration-tom/blob/36cb3ec0a163d4626e436560f8107dc38a13e4b4/calibrations/models.py#L20

The equivalent, which I just tried, would be this:

```python
In [1]: Target.objects.all()
Out[1]: <QuerySet [<Target: HD16160>, <Target: HD76151>, <Target: HD126053>, <Target: HD210988>, <Target: HR9087>, <Target: HR1544>, <Target: HR3454>, <Target: HR5501>, <Target: HR7596>, <Target: L92>, <Target: SA93>, <Target: L94>, <Target: L95>, <Target: SA95>, <Target: RU149>, <Target: SA101>, <Target: SA103>, <Target: L104>, <Target: L107>, <Target: SA108>, '...(remaining elements truncated)...']>

In [2]: meta = getattr(Target, '_meta')

In [3]: meta.ordering
Out[3]: ('id',)

In [4]: meta.ordering = ('-created',)

In [5]: setattr(Target, '_meta', meta)

In [6]: print(Target.objects.all())
<QuerySet [<Target: SA114>, <Target: L113>, <Target: SA112>, <Target: L110>, <Target: SA109>, <Target: SA108>, <Target: L107>, <Target: L104>, <Target: SA103>, <Target: SA101>, <Target: RU149>, <Target: SA95>, <Target: L95>, <Target: L94>, <Target: SA93>, <Target: L92>, <Target: HR7596>, <Target: HR5501>, <Target: HR3454>, <Target: HR1544>, '...(remaining elements truncated)...']>
```

I think the best alternative to the above would be to introduce a settings dictionary for each TOM module, much like the rest framework, and include in the `tom_targets` one an ordering that would be used in any list views.

**Comment by Fingel** [comment]
Would you consider just changing the ordering on the target list view to creation date, descending? I can't imagine there is anyone who uses the stock target list and wants to see oldest targets first?

**Comment by dmcollom** [comment]
Actually, if you click on the calibration-tom link, it's specifically done in the models.

Either way, yeah, I made the change in ``2.7.0``, give it five-ish minutes and the PyPi release will be done. The only thing that was giving me pause is that there are other potential ordering schemes (i.e. alphabetical, or last modified), but it would be overengineering to consider those until we have a need, and extending the view isn't hard anyway.

**Comment by Fingel** [comment]
Thanks David!
