### ISSUE TITLE
Facility Status makes target pages slow to load

### ISSUE THREAD

**Issue by Fingel** [TOMToolkit/tom_base#484]
I've noticed that individual target detail pages can sometimes take a very long time to load, 3-5 seconds usually. I found that the culprit is the "facility status" tab. Removing it causes the target detail pages to load in much less time.

I'm not sure if it's the API call on LCO's end or if the TOM is making too many requests, but quickly viewing targets is just not practical. I'd suggest (and what I'll be doing in my TOM) is moving facility status to a top level page instead of including it on every target page. That way the target pages load quickly but the facility status can still be checked, but will have less of an impact if it's slow to load, especially since the facility status doesn't seem to have a relation with a specific target anyway.

**Comment by dmcollom** [comment]
Fixed in #489 and released in `2.8.0`.
