### ISSUE TITLE
Error in running Lasair broker query

### ISSUE THREAD

**Issue by brendanrmills** [TOMToolkit/tom_base#547]
**Describe the bug**
When you run a alert query using the Lasair Broker, a JSON decode error is thrown. 

**To Reproduce**
1. install TOM and run server
2. Navigate to Alerts page
3. Create new Lasair Query (cone search or SQL query both produce the same error)
4. Run query on the query list page

**Expected behavior**
When you run the Lasair alerts query, it should generate a list of alerts that should be displayed so we can select targets. 

**Screenshots**
Creating the Lasair Broker
![Screenshot from 2022-06-17 17-27-10](https://user-images.githubusercontent.com/107709547/174348685-0dd8c045-7e06-44c4-9a96-1667f42d722a.png)

Error Running the broker
![Screenshot from 2022-06-17 17-27-28](https://user-images.githubusercontent.com/107709547/174348742-18cca0fa-8815-4302-8f95-1a424243a747.png)

**Desktop (please complete the following information):**
CentOS Linux release 7.9.2009 (Core)

**Comment by griffin-h** [comment]
I ran into this a couple of months ago, and I believe it's because the Lasair API has changed since the Lasair module in the TOM Toolkit was written. See https://lasair-ztf.lsst.ac.uk/api.
