### ISSUE TITLE
Querying the MARS broker crashes MARS

### ISSUE THREAD

**Issue by brendanrmills** [TOMToolkit/tom_base#548]
**Describe the bug**
I was using a management command to query MARS for a specific target. This usually look a few seconds but sometimes it would take over a minute. The code would often error because of something unrelated (my own mishaps) but when I would run the command again the server would be down. Going to mars.lco.global would yield a 503 error. 

**To Reproduce**
1.Install TOM
2. Prepare a management command according to the screenshot
3. run the command via terminal
4. Sometimes it will error sometimes it will not. I am still not sure what is causing the crash

**Expected behavior**
The code attached is a management command that should delete a target from the target list. The script calls the broker and runs a fetch_alerts method. We cast to a list and I have a print statement sanity check. 

**Screenshots**
Error message 
![Screenshot from 2022-06-17 23-39-22](https://user-images.githubusercontent.com/107709547/174412955-c967a53e-7111-46e9-a2d1-5ac2db59bcb5.png)
management command
![Screenshot from 2022-06-17 23-39-30](https://user-images.githubusercontent.com/107709547/174412956-4d5d1ff3-7984-4dad-b156-769a7ab45e57.png)
Error message from terminal
![Screenshot from 2022-06-17 23-52-10](https://user-images.githubusercontent.com/107709547/174413494-1d7f24ad-5ef9-45da-93f3-d553c0007f50.png)

**Desktop (please complete the following information):**
CentOS 7.9.2009

**Additional context**
I don't know exactly what triggers the crash but I will continue working on it. and I will update the issue report as I learn more.

**Comment by jchate6** [comment]
@phycodurus Am I correct that this is because Mars has been Mothballed and the broker is removed in the linked PR?

**Comment by phycodurus** [comment]
yes. Closing this issue: MARS has been retired under a "Mission Accomplished" banner. [ANTARES](https://antares.noirlab.edu/) is now the appropriate broker to query for alerts from the ZTF survey.
