### ISSUE TITLE
Photometry plot does not render as initial tab on target detail page

### ISSUE THREAD

**Issue by griffin-h** [TOMToolkit/tom_base#573]
I customized my TOM to show the photometry tab first when loading a target detail page by moving the "active" class from "observe-tab" to "photometry-tab":

```html
<li class="nav-item">
  <a class="nav-link active" id="photometry-tab" href="#photometry" role="tab" data-toggle="tab">Photometry</a>
</li>
<li class="nav-item">
  <a class="nav-link" id="spectroscopy-tab" href="#spectroscopy" role="tab" data-toggle="tab">Spectroscopy</a>
</li>
<li class="nav-item">
  <a class="nav-link" id="observe-tab" href="#observe" role="tab" data-toggle="tab">Observe</a>
</li>
```

This works to make that the default tab. However, the photometry plot does not initially load. You have to click to a different tab and then back to this tab to get it to load. Is there something else I need to change to get this to render automatically?

I discussed this with @phycodurus last week and he asked me to open a low-priority issue to remind him to look into it.

**Comment by phycodurus** [comment]
Thanks, Griffin, for taking the time to submit the issue and reminding me!

**Comment by rachel3834** [comment]
This seems related to issue #697

**Comment by jchate6** [comment]
@griffin-h Sorry I'm just getting to this. Did you also set the tab-pane to active?
```
<div class="tab-pane active" id="photometry">
        {% photometry_for_target target %}
        {% get_photometry_data object %}
</div>
```
If you didn't do this, then even though the photometry tab is selected, the html associated with the observe tab will be visible on load. You would then need to select a different tab to sync things again before you could actually display the photometry which sounds like it might be your issue.

I also want to point out that with `tomtoolkit 2.15.12` we have added the ability to set the initial tab by adding `?tab=photometry` (or whatever tab you are looking for) after the URL. 

Part of the motivation for this was to maintain the tab on a page refresh and to allow us to redirect to specific tabs after certain tasks are done. This could be useful when redirecting from any pages you've overwritten if you include these changes in Saguaro.

Would you find it a useful feature for us to include something like a `DEFAULT_TARGET_DETAIL_TAB` in the `settings.py` to use as the default active tab for users so this wouldn't have to be overwritten by individual users?

**Comment by griffin-h** [comment]
> @griffin-h Sorry I'm just getting to this. Did you also set the tab-pane to active?
> 
> ```
> <div class="tab-pane active" id="photometry">
>         {% photometry_for_target target %}
>         {% get_photometry_data object %}
> </div>
> ```
> 
> If you didn't do this, then even though the photometry tab is selected, the html associated with the observe tab will be visible on load. You would then need to select a different tab to sync things again before you could actually display the photometry which sounds like it might be your issue.

I didn't do this, but I just tried it, and it still doesn't work. As the page is loading, it initially looks like it's going to work, but then it snaps back to the built-in default tab (which I think is the first tab).

> I also want to point out that with `tomtoolkit 2.15.12` we have added the ability to set the initial tab by adding `?tab=photometry` (or whatever tab you are looking for) after the URL.
> 
> Part of the motivation for this was to maintain the tab on a page refresh and to allow us to redirect to specific tabs after certain tasks are done. This could be useful when redirecting from any pages you've overwritten if you include these changes in Saguaro.

This is definitely useful! I would use it when redirecting back to the target page from custom pages I've written.

> Would you find it a useful feature for us to include something like a `DEFAULT_TARGET_DETAIL_TAB` in the `settings.py` to use as the default active tab for users so this wouldn't have to be overwritten by individual users?

Yes, this would also be useful! Otherwise I don't know a way to set the default tab via the `?tab=photometry` method without overwriting the target list page to change all the links there. (If I'm missing something, let me know.)

**Comment by jchate6** [comment]
Resolved by setting the tab-pane to active and implementing the updated target detail javascript from tomtoolkit >= 2.15.12

The additional work of a customizable default tab has been spun off into Issue #783
