### ISSUE TITLE
Introduce Poetry

### ISSUE THREAD

**Issue by phycodurus** [TOMToolkit/tom_base#577]
See discussion in PR #568

**Comment by jchate6** [comment]
Python 3.7 will be supported for another 5 months.
https://devguide.python.org/versions/

Will be a good excuse for adding [Poetry](https://python-poetry.org/docs/dependency-specification/#multiple-constraints-dependencies)

**Comment by jchate6** [comment]
We would need to conditionally restrict numpy to 1.22 if using python 3.7
We would also need to run tests on 3.7
