### ISSUE TITLE
Prevent or discourage target creation for existing targets

### ISSUE THREAD

**Issue by dmcollom** [TOMToolkit/tom_base#70]
Before creating targets, users should have some indication that a target already exists or may already exist in order to avoid populating their TOM with duplicate data.

This should apply to all methods of target creation, including catalog import, catalog search, and broker ingestion.

**Comment by dmcollom** [comment]
So, first of all, I am unfortunately no longer with LCO, and am simply a bystander now trying to find enough spare time to contribute. @phycodurus is the new main point of contact.

This is still a relevant issue, but when you ask about how to approach it, are you talking about handling the current omission of this functionality in your own TOM, or contributing this functionality? If it's the former, you can potentially pre-empt any issues by doing a cone search and potentially any range searches on other attributes to do a `Target.objects.filter` and see if the queryset is empty. I'd need to see your code to really understand how you're using the `Target` model in order to know if that would definitively work, though.

If you're looking at the latter case, the way I would implement this in its simplest form would be to use the cone search utility function to search for targets in the same area. A TOM-level setting for conflict radius would be put in `settings.py` and used for the check, which would probably live in `tom_targets.models.Target.save()`, and the `save()` function would raise a particular exception that would need to be handled by any scripts or views that would encounter the error. It should be mentioned that the cone search functionality is currently being moved to be more broadly usable--that refactor is in `dev` for the moment. 

I'm sure that there are use cases beyond conflicting location (such as name conflict, which we handle to a degree), but I'm not aware of them, and I think the cone search use case is probably the predominant use case that should be handled first.

Does that help? If not, feel free to link us to the relevant code where you're experiencing issues, and I'd be happy to help.

**Comment by jchate6** [comment]
@johannct I believe this issue will be resolved with PR #593.
Once this PR is released, anytime `Target.validate_unique()` is run (usually as part of [`full_clean()`](https://docs.djangoproject.com/en/4.1/ref/models/instances/#django.db.models.Model.full_clean) just prior to saving) the target name or alias will be checked against every other name and alias in your DB to ensure that they are different. 
_Note:_ This check is case insensitive, and will ignore spaces, dashes, underscores, and parentheses. (i.e. `T-87a` will be treated as the same as `t_87a`)
