### ISSUE TITLE
Integrate TNS reporting

### ISSUE THREAD

**Issue by phycodurus** [TOMToolkit/tom_base#713]
see Issue #704 for an overview of Griffin's upcoming Contributions.

**Comment by jchate6** [comment]
[Saguaro TOM](https://sand.as.arizona.edu/saguaro_tom/) 

[Relevant Commits](https://github.com/SAGUARO-MMA/saguaro_tom/commit/0aa9ac1dcd9ed1ace09acf223d9a8282f48f4bbf) to Saguaro TOM that might be useful

**Comment by jchate6** [comment]
Relevant TNS Code in Saguaro:
[TNS Forms](https://github.com/SAGUARO-MMA/saguaro_tom/blob/main/custom_code/forms.py)
[TNS Classification HTML](https://github.com/SAGUARO-MMA/saguaro_tom/blob/main/templates/tom_targets/targetclassify_form.html)
[TNS Report HTML](https://github.com/SAGUARO-MMA/saguaro_tom/blob/main/templates/tom_targets/targetreport_form.html)
[Updated Buttons](https://github.com/SAGUARO-MMA/saguaro_tom/blob/main/templates/tom_targets/partials/target_buttons.html)

**Comment by jchate6** [comment]
@griffin-h
