### ISSUE TITLE
Single-target ingest from alert broker workflow

### ISSUE THREAD

**Issue by rachel3834** [TOMToolkit/tom_base#735]

**Comment by rachel3834** [comment]
Reported on TOM public slack channel by Dan Avner:

Hey TOMToolkit team, we (cc'ing 
[@Monika Soraisam](https://tom-toolkit.slack.com/team/U01JJRACE9Y)
) noticed that when we create just one target from a broker query, the user gets redirected to the tom_targets:update view. It kind of threw me off a bit because I thought the target was only half-created and I still needed to hit 'Save'. It wasn't super clear that the target was actually fully created at that point.
Here's the code I'm talking about: [Code Line Link](https://github.com/TOMToolkit/tom_base/blob/e521f40e08cf20cc3eeb253e1d2bceda92691d61/tom_alerts/views.py#L305)
How do you feel about simplifying this and just send everyone back to the tom_targets:list view unless all alerts fail? That way there's no confusion. (edited) 


        if (len(alerts) == len(errors)):
            return redirect(reverse('tom_alerts:run', kwargs={'pk': query_id}))
        elif (len(alerts) == 1):
            return redirect(reverse(
                'tom_targets:update', kwargs={'pk': target.id})
            )
        else:
            return redirect(reverse(
                'tom_targets:list')
            )
Would turn into:
        if (len(alerts) == len(errors)):
            return redirect(reverse('tom_alerts:run', kwargs={'pk': query_id}))

    return redirect(reverse(
        'tom_targets:list')
    )

**Comment by jchate6** [comment]
@davner

**Comment by jchate6** [comment]
@davner Do you have a strong opinion about redirecting to the list page rather than the target detail page for the new target?

**Comment by davner** [comment]
@jchate6 I believe always redirecting to the list page is the best option. It keeps it consistent whether you add one target or multiple.
