### ISSUE TITLE
Configurable Data Product Storage Path Including Observation ID

### ISSUE THREAD

**Issue by davner** [TOMToolkit/tom_base#754]
**Is your feature request related to a problem? Please describe.**
Hi TOM team, it’s been smooth sailing overriding specific parts of TOMToolkit to meet my project's needs, trying to avoid forking and maintaining my own version. However, I’ve encountered a need to change how data products are stored. Currently, the structure is `target/facility/filename`, but for our purposes, a structure like `target/facility/observation_id/filename` would be more beneficial.

From my perspective, the benefits are:

1. **Human-readable Hierarchical Structure:** This structure makes it easier to understand the relationship between targets, facilities, observations, and their respective data.
2. **Database Recovery:** In the event of database issues, the filesystem structure containing the observation ID would significantly aid in data recovery.
3. **Simplified Data Pipeline:** As we extend our project to include more complex data analysis and integrate with tools like the DRAGONS pipeline, having data organized by observation ID simplifies processing for Gemini's DRAGONS.

**Describe the solution you'd like**
One solution could introduce an option in `settings.py` allowing users to select between the current data saving path and the proposed one. The modification seems to be centered around the function `def data_product_path(instance, filename):` in `tom_dataproducts.models`. This would reduce the impact on existing installations.

We’re also open to alternative solutions or suggestions from the TOM team and the community.

**Comment by jchate6** [comment]
@davner Thanks for this issue. 
I think we'll need a way to make this truly configurable. 
Right now we are focused on preparing for the TOM toolkit workshop at AAS in January, but we will try to come up with a solution early in the new year.

**Comment by davner** [comment]
@jchate6 I understand. Do you have suggestions on how to override the `DataProduct` model `upload_to`? I've been trying to avoid forking and maintaining my own `tom_base` but my attempts at patching have not worked.
