### ISSUE TITLE
Inconsistent usage of "error" or "magnitude_error" in ReducedDatum.value

### ISSUE THREAD

**Issue by griffin-h** [TOMToolkit/tom_base#790]
**Describe the bug**
It appears that some parts of the code use "error" and others use "magnitude_error" for the uncertainty on the magnitude of a photometry point. For example, the photometry plot uses "error," but the photometry table uses "magnitude_error."

**To Reproduce**
1. Go to a target detail page with photometry
2. Click on the photometry tab
3. See some points with error bars plotted in the figure
4. Find those points in the table and see that they do not have errors listed

**Expected behavior**
I believe "error" was the original keyword used in the toolkit, because that is what's in the plot and what is parsed from photometry uploads. So I'd suggest replacing "magnitude_error" with "error" in `atlas_processor.py`, `alertstreams/hermes.py` and `dataproduct_extras.py` (and anywhere else I missed).

**Comment by jchate6** [comment]
This is related to Issue #609
