### ISSUE TITLE
Spectrum data processor needs facility identifier

### ISSUE THREAD

**Issue by rachel3834** [TOMToolkit/tom_base#811]
**Describe the bug**
The TOM's default sample spectrum CSV cannot be ingested by the data processor.  

**To Reproduce**
When I try to upload the spectrum_sample.csv file that is provided by default with the TOM through the Manage Data tab of a target detail page, I get an error, reporting that an "error occurred during the processing". 

**Expected behavior**
The upload of the given sample spectrum should work cleanly.

**Comment by jchate6** [comment]
resolved in PR #810
