### ISSUE TITLE
Bot-proofing TOMs deployed on public servers

### ISSUE THREAD

**Issue by rachel3834** [TOMToolkit/tom_base#850]
**Describe the bug**
As an example of a running TOM system, MOP has been experiencing a high query load, periodically.  
Monitoring by Jashan reports that many requests are coming from an external bot or web-crawler hitting URLs like ../alerts/query/xxx/run/ 
Although MOP correctedly returned 404 to the bot each time, the load was enough to cause MOP to do a silent restart (presumed to be because the container hit the memory limit).  
Jashan recommends ensuring that the TOM isn't doing any prefetching of data for non-authorized users, and otherwise minimizing the impact of bots like this.  
He also suggests adding a robots.txt which might limit the impact of at least good-citizen bots.

**Comment by jchate6** [comment]
a `robots.text` page was added to tom base 
See PR #858
