### ISSUE TITLE
Astroquery v0.4.7

### ISSUE THREAD

**Issue by rachel3834** [TOMToolkit/tom_base#872]
**Describe the bug**
The most recent version of astroquery appears to have changed the caching behaviour of Vizier queries.  In v0.4.6 Vizier query objects have a cache_location parameter which can be set to None to switch off caching.  This is desirable when a TOM is deployed to a Cloud-based server for example, since setting a cache location is a little more complicated and can incur additional charges.  

Reviewing the current astropy documentation, it was not immediately obvious how this behavior can be configured in the newer version.

**Comment by jchate6** [comment]
See #871

**Comment by jchate6** [comment]
We have bumped the poetry.lock version of Astroquery to 0.4.7
We still support earlier versions of astroquery, but vizier is not used in TomBase.
If you run into the above issue, you may need to restrict the astroquery version to `astroquery = "<0.4.7"` in your TOM.
