### ISSUE TITLE
Review contributed tom_keck facility module

### ISSUE THREAD

**Issue by rachel3834** [TOMToolkit/tom_base#883]
Chien-Hsiu Lee of the Keck Observatory has developed a TOM facility module to enable users to submit ToO and Classical mode observations to Keck telescopes. The repository is [here](https://github.com/lchjoel1031/tom_keck).  

Integrating this with the TOM Toolkit would be highly advantageous for users, so the first step is to review this repository.  
Reference information on observing with the Keck Observatory can be found [here](https://keckobservatory.org/about/observing).

**Comment by jchate6** [comment]
Deploy to TOM Demo

**Comment by jchate6** [comment]
Initial review of the tom_keck module completed, discussion is ongoing with the Keck team about full integration.
