### ISSUE TITLE
Clarify naming: forced photometry vs catalog search

### ISSUE THREAD

**Issue by phycodurus** [TOMToolkit/tom_base#894]
On the TargetDetail page Manage Data tab, we should not conflate catalog searches with actual forced photometry in the Form section headers; also in the documentation.

**Comment by jchate6** [comment]
- [ ] Generalize Forced photometry wording on Target Detail page
- [ ] Generalize forced photometry wording in settings.py
- [ ] refactor backend tom_dataproducts to be more general.
- [ ] update docs
