### ISSUE TITLE
Valid coordinates produce OutOfRange error in Target match_cone_search

### ISSUE THREAD

**Issue by rachel3834** [TOMToolkit/tom_base#932]
**Describe the bug**
I've written a management command to search my TOM for duplicate targets, based on spatial proximity. 
Working through all targets in the database, I am doing a cone search around the coordinates of each target to see if there are nearby objects within 2 arcsec. 

```
nearby_targets = Target.matches.match_cone_search(
                    float(working_target.ra),
                    float(working_target.dec),
                    radius)

```

This works fine for a number of targets, but fails (full error below) for target OGLE-2023-BLG-0002 RA=268.5057083333333, Dec=-28.44886111111111 and a radius of 2.0 [arcsec]. 

It's not clear to me why this is failing for valid input coordinates.

Searching for duplicates within 2.0arcsec of OGLE-2023-BLG-0002 RA=268.5057083333333, Dec=-28.44886111111111
Traceback (most recent call last):
  File "/data/software/mop_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NumericValueOutOfRange: input is out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/software/mop/./manage.py", line 21, in <module>
    main()
  File "/data/software/mop/./manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/data/software/mop_venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/data/software/mop_venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/data/software/mop_venv/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/data/software/mop_venv/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/data/software/mop/mop/management/commands/associate_duplicate_events.py", line 40, in handle
    logger.info(' -> Found ' + str(nearby_targets.count()) + ' in proximity to ' + working_target.name)
  File "/data/software/mop_venv/lib/python3.10/site-packages/django/db/models/query.py", line 608, in count
    return self.query.get_count(using=self.db)
  File "/data/software/mop_venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 568, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
  File "/data/software/mop_venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 554, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/data/software/mop_venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/data/software/mop_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/data/software/mop_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/data/software/mop_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/data/software/mop_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/data/software/mop_venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/data/software/mop_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: input is out of range

**Comment by jchate6** [comment]
This is interesting...
Can you please share the branch that has the `associate_duplicate_events` management command?
I'd also be interested in what would happen if you printed the query results for `nearby_targets` when pointed at `OGLE-2023-BLG-0002`

**Comment by rachel3834** [comment]
Sure, the branch is this one: https://github.com/LCOGT/mop/tree/feature/match_duplicate_events

I've tried to print the nearby_target query results but the code is failing in the match_cone_search, so no results are returned. 

The weird thing is, it works just fine with other example targets.  E.g. using OGLE-2023-GD-0011 as a test, I get:

```
Searching for duplicates within 2.0arcsec of OGLE-2023-GD-0011 RA=244.60583333333332, Dec=-54.078833333333336
<QuerySet [<BaseTarget: OGLE-2023-GD-0011>, <BaseTarget: Gaia24amk>]>
 -> Found 2 in proximity to OGLE-2023-GD-0011
 -> Primary target name: OGLE-2023-GD-0011
 -> Matches with duplicates: []
Target post save hook: OGLE-2023-GD-0011 created: False
 -> Merged extra_params
 -> Completed merge of data products for OGLE-2023-GD-0011 with matching objects
 -> Completed transfer of observation records to OGLE-2023-GD-0011
 -> Merged comments for OGLE-2023-GD-0011
```

**Comment by jchate6** [comment]
> I've tried to print the nearby_target query results but the code is failing in the match_cone_search, so no results are returned.

The above stack trace implies the issue happens when performing the `.count()` on line 40.

Any chance you could get me credentials to look at this MOP DB? My understanding is that usually that error happens when you try to access or store values in an integer field that require a 64-bit integer field. (larger than +/- 2147483647).

I'd also be interested in if it works when you manually enter those coordinates into the cone search filter on the target list page.

**Comment by rachel3834** [comment]
The coordinate fields are held as floats so I'm not sure how a large integer error might be coming in here.  When I put the same coordinates and radius into the target list page search box, it correctly returns the two targets expected to match.

**Comment by rachel3834** [comment]
One point to note is that the issue is seen on my (updated) test version of MOP rather than the production MOP which has not yet been updated to the related alpha release. However, the usual target list search works for both systems. 

Some interesting results from a unit test designed to specifically test the Target.matches.match_cone_search method.  

Unit test:
```
    def setUp(self):
        self.target_coordinates = [
            [244.60583333333332, -54.078833333333336, 'OGLE-2023-GD-0011'],
            [276.2508, -21.0287, 'OGLE-2024-BLG-0002'],
            [260.3587, -29.4469, 'OGLE-2024-BLG-0280'],
            [268.5057, -28.44886, 'OGLE-2023-BLG-0002'],
            [268.5057083333333, -28.44886111111111, 'OGLE-2023-BLG-0002']
        ]
        self.radius = 2.0   # Arseconds

        for target in self.target_coordinates:
            t = SiderealTargetFactory.create()
            t.ra = target[0]
            t.dec = target[1]
            t.save()

    def test_match_cone_search(self):
        for target in self.target_coordinates:
            print('Searching on target coordinates for ' + target[2] + ' ' + str(target[0]) + ' ' + str(target[1]))
            nearby_targets = Target.matches.match_cone_search(
                target[0],
                target[1],
                self.radius)

            assert(len(nearby_targets) > 0)
```

Output:
```
Searching on target coordinates for OGLE-2023-GD-0011 244.60583333333332 -54.078833333333336
Searching on target coordinates for OGLE-2024-BLG-0002 276.2508 -21.0287
Searching on target coordinates for OGLE-2024-BLG-0280 260.3587 -29.4469
Searching on target coordinates for OGLE-2023-BLG-0002 268.5057 -28.44886
Searching on target coordinates for OGLE-2023-BLG-0002 268.5057083333333 -28.44886111111111
E
======================================================================
ERROR: test_match_cone_search (tests.test_cone_search.TestMergeExtraParams)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/software/mop_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NumericValueOutOfRange: input is out of range
```

Note the last two entries are searching for the same object and coordinates, I just curtailed the number of decimal places in the RA and Dec floating point values.

**Comment by rachel3834** [comment]
Continuing this test on the test-MOP instance simply by introducing rounding on the coordinate strings:

```
nearby_targets = Target.matches.match_cone_search(
                    round(float(working_target.ra),5),
                    round(float(working_target.dec),5),
                    radius)
                print(nearby_targets)
```

Produces the following output for the target previously causing trouble:
```
Searching for duplicates within 2.0arcsec of OGLE-2023-BLG-0002 RA=268.5057083333333, Dec=-28.44886111111111
<QuerySet [<BaseTarget: OGLE-2023-BLG-0002>]>
```

This workaround apparently resolves this issue.  

Speculation: under the hood, the match manager is splitting the coordinate string into integers, perhaps to make the search more efficient, and the length of the full coordinates is exceeding the integer limits?  Note that the coordinates are usually being input as sexigesimal strings and converted to decimal degrees on ingest, so this is purely a numerical handling issue.

**Comment by rachel3834** [comment]
Here's my test venv pip freeze output for reference.

[tmp_mop_venv.txt](https://github.com/TOMToolkit/tom_base/files/15358753/tmp_mop_venv.txt)

**Comment by rachel3834** [comment]
For reference, this error was first discovered on my Ubuntu-linux desktop so as an extra datapoint I tried the same tests after installing MOP on my Mac laptop.  The test fails with the same error.  I will also note that while the default test DB set up would be an SQLite3 DB, my local settings defines the test DB to be a postgres one.

**Comment by rachel3834** [comment]
I wonder if [this](https://blog.francium.tech/postgress-numericvalueoutofrange-ad7bcb01f2f8) is relevant?  The strings that my query is breaking on include 18 digits, including the minus sign for the Dec value.

**Comment by rachel3834** [comment]
7 decimal places in decimal degrees corresponds to 3.6 milliarcsec.  For most users that is fine, but the best precision astrometry of astronomical objects is ~few milliarcsec, so this could be a problem for some users.  So it is worth considering ensuring that the TOM handles coordinate strings as double precision floats.

**Comment by jchate6** [comment]
I have figured out the issue here. I'm working on a fix.
It has to do with the adding of the separation to the queryset as a float when the target is being matched with its own coordinates. There is some floating point arithmetic issues that lead to this being a very VERY tiny number that is not 0, and requires more than double precision when the full double precision is used in the original number.
We try to store the separation in the queryset as a float, but it won't fit, thus error.
