### ISSUE TITLE
App to interactively add spectral lines to Spectroscopy plots 

### ISSUE THREAD

**Issue by jchate6** [TOMToolkit/tom_base#935]
Saguaro TOM would like to incorporate the SNEX2 capability to use plotly to add certain spectral lines to spectroscopy plots.

See https://github.com/LCOGT/snex2/blob/master/custom_code/dash_apps/spectra.py

**Comment by jchate6** [comment]
@griffin-h @cmccully 
Can you please add comments describing the specific issues you ran into trying to implement this?

**Comment by griffin-h** [comment]
Possibly a duplicate of #861?
