### ISSUE TITLE
Querying custom targets on targetname

### ISSUE THREAD

**Issue by rachel3834** [TOMToolkit/tom_base#950]
**Question rather than a bug**
I have implemented a custom Target model which extends the BaseTarget object with extra parameters such as classification.  My targets often have multiple names.  I need to perform a DB query to retrieve all targets with one or more TargetNames including 'Gaia' and the classification of microlensing.  Summarizing in a code snippet:

```
class MicrolensingTarget(BaseTarget):
    """
    Customized Target model including attributes relating the observation and modeling of microlensing events
    """

    # Microlensing-specific fields
    alive = models.BooleanField(default=True)
    classification = models.CharField(max_length=50, default='Microlensing PSPL')
  <snip>

class TargetName(models.Model):
    target = models.ForeignKey(BaseTarget, on_delete=models.CASCADE, related_name='aliases')
    name = models.CharField(max_length=100, unique=True, verbose_name='Alias')
  <snip>
```

So I tried to form this query on the TargetNames table like this:
```
qs = TargetName.objects.filter(
        name__icontains='Gaia',
        target__classification__icontains='Microlensing',
    )
```

But this produces an error:
```
django.core.exceptions.FieldError: Unsupported lookup 'classification' for ForeignKey or join on the field not permitted.
```

It wasn't clear to me why this wasn't valid, but I see that the TargetName inherits the BaseTarget model rather than my custom Target model, and so presumably doesn't have access to the additional attributes. 

Advice on the most efficient ways to perform lookups like this would be very helpful.

**Comment by jchate6** [comment]
Is it possible you missed a migration?

**Comment by rachel3834** [comment]
Thanks Joey.  It looks like the aliases search term was the one I needed; I didn't realize that was the direction to take.  I've implemented the query you outlined with the Q function and that does work.  Thanks for your help!
