### ISSUE TITLE
Please add a license to this repository

### ISSUE THREAD

**Issue by arfon** [TOMToolkit/tom_base#96]
:wave: very nice work here!

Would you be willing to add an [open source license](https://choosealicense.com/) to this repository so that potential reuse terms are more clear? Unless you have a strong opinion about this, I'd recommend adopting the BSD 3-Clause license which is popular in scientific python communities (Astropy uses this).

**Comment by Fingel** [comment]
Hi @arfon,
Good point, we should add a license. I'll bring it up with the rest of the contributors and we can decide which one is the best fit.

**Comment by Fingel** [comment]
After a brief discussion we settled on using the GPL.
