### ISSUE TITLE
overlay aladin on the white skymap

### ISSUE THREAD

**Issue by sglasberg** [TOMToolkit/tom_base#980]
Overlay aladin on white skymap to be able to use more functions. The target list will be seen on aladin

There were functions and variables named aladin. Changed anything named aladin to aladin_finderchart to make room for aladin_skymap.

**Comment by jchate6** [comment]
We should make sure that the new skymap:

- [ ] Doesn't break when non-sidereal targets are on the list
- [ ] Only plots the targets on the first page (if you have hundreds of targets in your data base, it only prints the first few)
- [ ] Doesn't break anyone else's target list page if they are currently referencing the old skymap.
